#pragma once

#include <stdbool.h>
#include <stdint.h>

// Core environment sizes and limits.
#define CRAFTAX_OBS_ROWS 9
#define CRAFTAX_OBS_COLS 11
#define CRAFTAX_MAP_SIZE 48
#define CRAFTAX_MAP_CELLS (CRAFTAX_MAP_SIZE * CRAFTAX_MAP_SIZE)
#define CRAFTAX_NUM_LEVELS 9

#define CRAFTAX_NUM_BLOCK_TYPES 37
#define CRAFTAX_NUM_ITEM_TYPES 5
#define CRAFTAX_NUM_MOB_CLASSES 5
#define CRAFTAX_NUM_MOB_TYPES 8
#define CRAFTAX_INVENTORY_OBS_SIZE 51

#define CRAFTAX_PACKED_CHANNELS_PER_CELL (3 + CRAFTAX_NUM_MOB_CLASSES)
#define CRAFTAX_PACKED_MAP_OBS_SIZE ( \
    CRAFTAX_OBS_ROWS * CRAFTAX_OBS_COLS * CRAFTAX_PACKED_CHANNELS_PER_CELL \
)
#define CRAFTAX_PACKED_OBS_SIZE ( \
    CRAFTAX_PACKED_MAP_OBS_SIZE + CRAFTAX_INVENTORY_OBS_SIZE \
)

#define CRAFTAX_OBS_SIZE CRAFTAX_PACKED_OBS_SIZE
#define CRAFTAX_NUM_ACTIONS 43
#define CRAFTAX_NUM_ACHIEVEMENTS 67

#define CRAFTAX_MAX_MELEE_MOBS 3
#define CRAFTAX_MAX_PASSIVE_MOBS 3
#define CRAFTAX_MAX_RANGED_MOBS 2
#define CRAFTAX_MAX_MOB_PROJECTILES 3
#define CRAFTAX_MAX_PLAYER_PROJECTILES 3
#define CRAFTAX_MAX_GROWING_PLANTS 10

#define CRAFTAX_DEFAULT_MAX_TIMESTEPS 100000
#define CRAFTAX_DAY_LENGTH 300
#define CRAFTAX_MAX_ATTRIBUTE 5
#define CRAFTAX_MOB_DESPAWN_DISTANCE 14
#define CRAFTAX_MONSTERS_KILLED_TO_CLEAR_LEVEL 8
#define CRAFTAX_BOSS_FIGHT_SPAWN_TURNS 7
#define CRAFTAX_BOSS_FIGHT_EXTRA_DAMAGE 0.5f
#define CRAFTAX_PI 3.14159265358979323846f

// Aliases shared by the overworld generation helpers.
#define CRAFTAX_OVERWORLD_SIZE CRAFTAX_MAP_SIZE
#define CRAFTAX_OVERWORLD_CELLS CRAFTAX_MAP_CELLS

// Rendering constants.
#define CRAFTAX_TEX_TILE_PX 16
#define CRAFTAX_TEX_SCALE 4
#define CRAFTAX_TEX_DRAW_PX (CRAFTAX_TEX_TILE_PX * CRAFTAX_TEX_SCALE)
#define CRAFTAX_FLOOR_TILE_PX 16
#define CRAFTAX_TEX_NUM (37 + 5 + 5 + 3 + 4)

#define CRAFTAX_RENDER_ROWS CRAFTAX_OBS_ROWS
#define CRAFTAX_RENDER_COLS CRAFTAX_OBS_COLS

#define CRAFTAX_TEX_PLAYER_DOWN 37
#define CRAFTAX_TEX_PLAYER_UP 38
#define CRAFTAX_TEX_PLAYER_LEFT 39
#define CRAFTAX_TEX_PLAYER_RIGHT 40
#define CRAFTAX_TEX_PLAYER_SLEEP 41
#define CRAFTAX_TEX_ITEM_BASE 42
#define CRAFTAX_TEX_MOB_BASE 47

#define CRAFTAX_VIEW_MODE_AGENT 0
#define CRAFTAX_VIEW_MODE_FLOOR 1
#define CRAFTAX_TRAIL_LEN 10
#define CRAFTAX_VEC_TILE_SIZE 128

// Spawn/update helper constants.
#define CRAFTAX_SPAWN_MAP_CELLS CRAFTAX_MAP_CELLS
#define CRAFTAX_SPAWN_BBOX_MAX_CELLS 729
#define CRAFTAX_SPAWN_ALL_VALID_BLOCK_MASK ( \
    (1ULL << CRAFTAX_BLOCK_GRASS) \
    | (1ULL << CRAFTAX_BLOCK_PATH) \
    | (1ULL << CRAFTAX_BLOCK_FIRE_GRASS) \
    | (1ULL << CRAFTAX_BLOCK_ICE_GRASS))
#define CRAFTAX_SPAWN_GRAVE_BLOCK_MASK ( \
    (1ULL << CRAFTAX_BLOCK_GRAVE) \
    | (1ULL << CRAFTAX_BLOCK_GRAVE2) \
    | (1ULL << CRAFTAX_BLOCK_GRAVE3))
#define CRAFTAX_SPAWN_WATER_BLOCK_MASK (1ULL << CRAFTAX_BLOCK_WATER)

// Enums copied from craftax/craftax/constants.py
typedef enum CraftaxBlockType {
    CRAFTAX_BLOCK_INVALID = 0,
    CRAFTAX_BLOCK_OUT_OF_BOUNDS = 1,
    CRAFTAX_BLOCK_GRASS = 2,
    CRAFTAX_BLOCK_WATER = 3,
    CRAFTAX_BLOCK_STONE = 4,
    CRAFTAX_BLOCK_TREE = 5,
    CRAFTAX_BLOCK_WOOD = 6,
    CRAFTAX_BLOCK_PATH = 7,
    CRAFTAX_BLOCK_COAL = 8,
    CRAFTAX_BLOCK_IRON = 9,
    CRAFTAX_BLOCK_DIAMOND = 10,
    CRAFTAX_BLOCK_CRAFTING_TABLE = 11,
    CRAFTAX_BLOCK_FURNACE = 12,
    CRAFTAX_BLOCK_SAND = 13,
    CRAFTAX_BLOCK_LAVA = 14,
    CRAFTAX_BLOCK_PLANT = 15,
    CRAFTAX_BLOCK_RIPE_PLANT = 16,
    CRAFTAX_BLOCK_WALL = 17,
    CRAFTAX_BLOCK_DARKNESS = 18,
    CRAFTAX_BLOCK_WALL_MOSS = 19,
    CRAFTAX_BLOCK_STALAGMITE = 20,
    CRAFTAX_BLOCK_SAPPHIRE = 21,
    CRAFTAX_BLOCK_RUBY = 22,
    CRAFTAX_BLOCK_CHEST = 23,
    CRAFTAX_BLOCK_FOUNTAIN = 24,
    CRAFTAX_BLOCK_FIRE_GRASS = 25,
    CRAFTAX_BLOCK_ICE_GRASS = 26,
    CRAFTAX_BLOCK_GRAVEL = 27,
    CRAFTAX_BLOCK_FIRE_TREE = 28,
    CRAFTAX_BLOCK_ICE_SHRUB = 29,
    CRAFTAX_BLOCK_ENCHANTMENT_TABLE_FIRE = 30,
    CRAFTAX_BLOCK_ENCHANTMENT_TABLE_ICE = 31,
    CRAFTAX_BLOCK_NECROMANCER = 32,
    CRAFTAX_BLOCK_GRAVE = 33,
    CRAFTAX_BLOCK_GRAVE2 = 34,
    CRAFTAX_BLOCK_GRAVE3 = 35,
    CRAFTAX_BLOCK_NECROMANCER_VULNERABLE = 36,
} CraftaxBlockType;

typedef enum CraftaxItemType {
    CRAFTAX_ITEM_NONE = 0,
    CRAFTAX_ITEM_TORCH = 1,
    CRAFTAX_ITEM_LADDER_DOWN = 2,
    CRAFTAX_ITEM_LADDER_UP = 3,
    CRAFTAX_ITEM_LADDER_DOWN_BLOCKED = 4,
} CraftaxItemType;

typedef enum CraftaxAction {
    CRAFTAX_ACTION_NOOP = 0,
    CRAFTAX_ACTION_LEFT = 1,
    CRAFTAX_ACTION_RIGHT = 2,
    CRAFTAX_ACTION_UP = 3,
    CRAFTAX_ACTION_DOWN = 4,
    CRAFTAX_ACTION_DO = 5,
    CRAFTAX_ACTION_SLEEP = 6,
    CRAFTAX_ACTION_PLACE_STONE = 7,
    CRAFTAX_ACTION_PLACE_TABLE = 8,
    CRAFTAX_ACTION_PLACE_FURNACE = 9,
    CRAFTAX_ACTION_PLACE_PLANT = 10,
    CRAFTAX_ACTION_MAKE_WOOD_PICKAXE = 11,
    CRAFTAX_ACTION_MAKE_STONE_PICKAXE = 12,
    CRAFTAX_ACTION_MAKE_IRON_PICKAXE = 13,
    CRAFTAX_ACTION_MAKE_WOOD_SWORD = 14,
    CRAFTAX_ACTION_MAKE_STONE_SWORD = 15,
    CRAFTAX_ACTION_MAKE_IRON_SWORD = 16,
    CRAFTAX_ACTION_REST = 17,
    CRAFTAX_ACTION_DESCEND = 18,
    CRAFTAX_ACTION_ASCEND = 19,
    CRAFTAX_ACTION_MAKE_DIAMOND_PICKAXE = 20,
    CRAFTAX_ACTION_MAKE_DIAMOND_SWORD = 21,
    CRAFTAX_ACTION_MAKE_IRON_ARMOUR = 22,
    CRAFTAX_ACTION_MAKE_DIAMOND_ARMOUR = 23,
    CRAFTAX_ACTION_SHOOT_ARROW = 24,
    CRAFTAX_ACTION_MAKE_ARROW = 25,
    CRAFTAX_ACTION_CAST_FIREBALL = 26,
    CRAFTAX_ACTION_CAST_ICEBALL = 27,
    CRAFTAX_ACTION_PLACE_TORCH = 28,
    CRAFTAX_ACTION_DRINK_POTION_RED = 29,
    CRAFTAX_ACTION_DRINK_POTION_GREEN = 30,
    CRAFTAX_ACTION_DRINK_POTION_BLUE = 31,
    CRAFTAX_ACTION_DRINK_POTION_PINK = 32,
    CRAFTAX_ACTION_DRINK_POTION_CYAN = 33,
    CRAFTAX_ACTION_DRINK_POTION_YELLOW = 34,
    CRAFTAX_ACTION_READ_BOOK = 35,
    CRAFTAX_ACTION_ENCHANT_SWORD = 36,
    CRAFTAX_ACTION_ENCHANT_ARMOUR = 37,
    CRAFTAX_ACTION_MAKE_TORCH = 38,
    CRAFTAX_ACTION_LEVEL_UP_DEXTERITY = 39,
    CRAFTAX_ACTION_LEVEL_UP_STRENGTH = 40,
    CRAFTAX_ACTION_LEVEL_UP_INTELLIGENCE = 41,
    CRAFTAX_ACTION_ENCHANT_BOW = 42,
} CraftaxAction;

typedef enum CraftaxMobType {
    CRAFTAX_MOB_PASSIVE = 0,
    CRAFTAX_MOB_MELEE = 1,
    CRAFTAX_MOB_RANGED = 2,
    CRAFTAX_MOB_PROJECTILE = 3,
} CraftaxMobType;

typedef enum CraftaxProjectileType {
    CRAFTAX_PROJECTILE_ARROW = 0,
    CRAFTAX_PROJECTILE_DAGGER = 1,
    CRAFTAX_PROJECTILE_FIREBALL = 2,
    CRAFTAX_PROJECTILE_ICEBALL = 3,
    CRAFTAX_PROJECTILE_ARROW2 = 4,
    CRAFTAX_PROJECTILE_SLIMEBALL = 5,
    CRAFTAX_PROJECTILE_FIREBALL2 = 6,
    CRAFTAX_PROJECTILE_ICEBALL2 = 7,
} CraftaxProjectileType;

typedef enum CraftaxAchievement {
    CRAFTAX_ACH_COLLECT_WOOD = 0,
    CRAFTAX_ACH_PLACE_TABLE = 1,
    CRAFTAX_ACH_EAT_COW = 2,
    CRAFTAX_ACH_COLLECT_SAPLING = 3,
    CRAFTAX_ACH_COLLECT_DRINK = 4,
    CRAFTAX_ACH_MAKE_WOOD_PICKAXE = 5,
    CRAFTAX_ACH_MAKE_WOOD_SWORD = 6,
    CRAFTAX_ACH_PLACE_PLANT = 7,
    CRAFTAX_ACH_DEFEAT_ZOMBIE = 8,
    CRAFTAX_ACH_COLLECT_STONE = 9,
    CRAFTAX_ACH_PLACE_STONE = 10,
    CRAFTAX_ACH_EAT_PLANT = 11,
    CRAFTAX_ACH_DEFEAT_SKELETON = 12,
    CRAFTAX_ACH_MAKE_STONE_PICKAXE = 13,
    CRAFTAX_ACH_MAKE_STONE_SWORD = 14,
    CRAFTAX_ACH_WAKE_UP = 15,
    CRAFTAX_ACH_PLACE_FURNACE = 16,
    CRAFTAX_ACH_COLLECT_COAL = 17,
    CRAFTAX_ACH_COLLECT_IRON = 18,
    CRAFTAX_ACH_COLLECT_DIAMOND = 19,
    CRAFTAX_ACH_MAKE_IRON_PICKAXE = 20,
    CRAFTAX_ACH_MAKE_IRON_SWORD = 21,
    CRAFTAX_ACH_MAKE_ARROW = 22,
    CRAFTAX_ACH_MAKE_TORCH = 23,
    CRAFTAX_ACH_PLACE_TORCH = 24,
    CRAFTAX_ACH_MAKE_DIAMOND_SWORD = 25,
    CRAFTAX_ACH_MAKE_IRON_ARMOUR = 26,
    CRAFTAX_ACH_MAKE_DIAMOND_ARMOUR = 27,
    CRAFTAX_ACH_ENTER_GNOMISH_MINES = 28,
    CRAFTAX_ACH_ENTER_DUNGEON = 29,
    CRAFTAX_ACH_ENTER_SEWERS = 30,
    CRAFTAX_ACH_ENTER_VAULT = 31,
    CRAFTAX_ACH_ENTER_TROLL_MINES = 32,
    CRAFTAX_ACH_ENTER_FIRE_REALM = 33,
    CRAFTAX_ACH_ENTER_ICE_REALM = 34,
    CRAFTAX_ACH_ENTER_GRAVEYARD = 35,
    CRAFTAX_ACH_DEFEAT_GNOME_WARRIOR = 36,
    CRAFTAX_ACH_DEFEAT_GNOME_ARCHER = 37,
    CRAFTAX_ACH_DEFEAT_ORC_SOLIDER = 38,
    CRAFTAX_ACH_DEFEAT_ORC_MAGE = 39,
    CRAFTAX_ACH_DEFEAT_LIZARD = 40,
    CRAFTAX_ACH_DEFEAT_KOBOLD = 41,
    CRAFTAX_ACH_DEFEAT_TROLL = 42,
    CRAFTAX_ACH_DEFEAT_DEEP_THING = 43,
    CRAFTAX_ACH_DEFEAT_PIGMAN = 44,
    CRAFTAX_ACH_DEFEAT_FIRE_ELEMENTAL = 45,
    CRAFTAX_ACH_DEFEAT_FROST_TROLL = 46,
    CRAFTAX_ACH_DEFEAT_ICE_ELEMENTAL = 47,
    CRAFTAX_ACH_DAMAGE_NECROMANCER = 48,
    CRAFTAX_ACH_DEFEAT_NECROMANCER = 49,
    CRAFTAX_ACH_EAT_BAT = 50,
    CRAFTAX_ACH_EAT_SNAIL = 51,
    CRAFTAX_ACH_FIND_BOW = 52,
    CRAFTAX_ACH_FIRE_BOW = 53,
    CRAFTAX_ACH_COLLECT_SAPPHIRE = 54,
    CRAFTAX_ACH_LEARN_FIREBALL = 55,
    CRAFTAX_ACH_CAST_FIREBALL = 56,
    CRAFTAX_ACH_LEARN_ICEBALL = 57,
    CRAFTAX_ACH_CAST_ICEBALL = 58,
    CRAFTAX_ACH_COLLECT_RUBY = 59,
    CRAFTAX_ACH_MAKE_DIAMOND_PICKAXE = 60,
    CRAFTAX_ACH_OPEN_CHEST = 61,
    CRAFTAX_ACH_DRINK_POTION = 62,
    CRAFTAX_ACH_ENCHANT_SWORD = 63,
    CRAFTAX_ACH_ENCHANT_ARMOUR = 64,
    CRAFTAX_ACH_DEFEAT_KNIGHT = 65,
    CRAFTAX_ACH_DEFEAT_ARCHER = 66,
} CraftaxAchievement;

typedef struct CraftaxSmoothGenConfig {
    int default_block;
    int sea_block;
    int coast_block;
    int mountain_block;
    int path_block;
    int inner_mountain_block;
    int ore_requirement_blocks[5];
    int ores[5];
    float ore_chances[5];
    int tree_requirement_block;
    int tree;
    int lava;
    int player_spawn;
    int valid_ladder;
    bool ladder_up;
    bool ladder_down;
    float player_proximity_map_water_strength;
    float player_proximity_map_water_max;
    float player_proximity_map_mountain_strength;
    float player_proximity_map_mountain_max;
    float default_light;
    float water_threshold;
    float sand_threshold;
    float tree_threshold_uniform;
    float tree_threshold_perlin;
} CraftaxSmoothGenConfig;

typedef struct CraftaxDungeonConfig {
    int special_block;
    int fountain_block;
    int rare_path_replacement_block;
} CraftaxDungeonConfig;

static const CraftaxSmoothGenConfig CRAFTAX_SMOOTHGEN_CONFIGS[6] = {
    {
        CRAFTAX_BLOCK_GRASS,
        CRAFTAX_BLOCK_WATER,
        CRAFTAX_BLOCK_SAND,
        CRAFTAX_BLOCK_STONE,
        CRAFTAX_BLOCK_PATH,
        CRAFTAX_BLOCK_PATH,
        {CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE},
        {CRAFTAX_BLOCK_COAL, CRAFTAX_BLOCK_IRON, CRAFTAX_BLOCK_DIAMOND, CRAFTAX_BLOCK_OUT_OF_BOUNDS, CRAFTAX_BLOCK_OUT_OF_BOUNDS},
        {0.03f, 0.02f, 0.001f, 0.0f, 0.0f},
        CRAFTAX_BLOCK_GRASS,
        CRAFTAX_BLOCK_TREE,
        CRAFTAX_BLOCK_LAVA,
        CRAFTAX_BLOCK_GRASS,
        CRAFTAX_BLOCK_PATH,
        false,
        true,
        5.0f,
        1.0f,
        5.0f,
        1.0f,
        1.0f,
        0.7f,
        0.6f,
        0.8f,
        0.5f,
    },
    {
        CRAFTAX_BLOCK_PATH,
        CRAFTAX_BLOCK_WATER,
        CRAFTAX_BLOCK_PATH,
        CRAFTAX_BLOCK_STONE,
        CRAFTAX_BLOCK_STONE,
        CRAFTAX_BLOCK_STONE,
        {CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE},
        {CRAFTAX_BLOCK_COAL, CRAFTAX_BLOCK_IRON, CRAFTAX_BLOCK_DIAMOND, CRAFTAX_BLOCK_SAPPHIRE, CRAFTAX_BLOCK_RUBY},
        {0.04f, 0.02f, 0.005f, 0.0025f, 0.0025f},
        CRAFTAX_BLOCK_PATH,
        CRAFTAX_BLOCK_STALAGMITE,
        CRAFTAX_BLOCK_LAVA,
        CRAFTAX_BLOCK_PATH,
        CRAFTAX_BLOCK_PATH,
        true,
        true,
        5.0f,
        1.0f,
        17.0f,
        1.5f,
        0.0f,
        0.7f,
        0.6f,
        0.8f,
        0.5f,
    },
    {
        CRAFTAX_BLOCK_PATH,
        CRAFTAX_BLOCK_WATER,
        CRAFTAX_BLOCK_PATH,
        CRAFTAX_BLOCK_STONE,
        CRAFTAX_BLOCK_STONE,
        CRAFTAX_BLOCK_STONE,
        {CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE},
        {CRAFTAX_BLOCK_COAL, CRAFTAX_BLOCK_IRON, CRAFTAX_BLOCK_DIAMOND, CRAFTAX_BLOCK_SAPPHIRE, CRAFTAX_BLOCK_RUBY},
        {0.04f, 0.03f, 0.01f, 0.01f, 0.01f},
        CRAFTAX_BLOCK_PATH,
        CRAFTAX_BLOCK_STALAGMITE,
        CRAFTAX_BLOCK_LAVA,
        CRAFTAX_BLOCK_PATH,
        CRAFTAX_BLOCK_PATH,
        true,
        true,
        5.0f,
        1.0f,
        17.0f,
        1.5f,
        0.0f,
        0.7f,
        0.6f,
        0.8f,
        0.5f,
    },
    {
        CRAFTAX_BLOCK_FIRE_GRASS,
        CRAFTAX_BLOCK_LAVA,
        CRAFTAX_BLOCK_SAND,
        CRAFTAX_BLOCK_STONE,
        CRAFTAX_BLOCK_STONE,
        CRAFTAX_BLOCK_STONE,
        {CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE},
        {CRAFTAX_BLOCK_COAL, CRAFTAX_BLOCK_IRON, CRAFTAX_BLOCK_DIAMOND, CRAFTAX_BLOCK_SAPPHIRE, CRAFTAX_BLOCK_RUBY},
        {0.05f, 0.0f, 0.0f, 0.0f, 0.025f},
        CRAFTAX_BLOCK_FIRE_GRASS,
        CRAFTAX_BLOCK_FIRE_TREE,
        CRAFTAX_BLOCK_LAVA,
        CRAFTAX_BLOCK_FIRE_GRASS,
        CRAFTAX_BLOCK_FIRE_GRASS,
        true,
        true,
        5.0f,
        1.0f,
        5.0f,
        1.0f,
        1.0f,
        0.5f,
        0.6f,
        0.8f,
        0.5f,
    },
    {
        CRAFTAX_BLOCK_ICE_GRASS,
        CRAFTAX_BLOCK_WATER,
        CRAFTAX_BLOCK_ICE_GRASS,
        CRAFTAX_BLOCK_STONE,
        CRAFTAX_BLOCK_STONE,
        CRAFTAX_BLOCK_STONE,
        {CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE, CRAFTAX_BLOCK_STONE},
        {CRAFTAX_BLOCK_COAL, CRAFTAX_BLOCK_IRON, CRAFTAX_BLOCK_DIAMOND, CRAFTAX_BLOCK_SAPPHIRE, CRAFTAX_BLOCK_RUBY},
        {0.0f, 0.0f, 0.005f, 0.02f, 0.0f},
        CRAFTAX_BLOCK_ICE_GRASS,
        CRAFTAX_BLOCK_ICE_SHRUB,
        CRAFTAX_BLOCK_WATER,
        CRAFTAX_BLOCK_ICE_GRASS,
        CRAFTAX_BLOCK_ICE_GRASS,
        true,
        true,
        5.0f,
        1.0f,
        17.0f,
        1.5f,
        0.0f,
        0.5f,
        0.6f,
        0.4f,
        0.5f,
    },
    {
        CRAFTAX_BLOCK_PATH,
        CRAFTAX_BLOCK_PATH,
        CRAFTAX_BLOCK_PATH,
        CRAFTAX_BLOCK_WALL,
        CRAFTAX_BLOCK_WALL,
        CRAFTAX_BLOCK_WALL,
        {CRAFTAX_BLOCK_WALL, CRAFTAX_BLOCK_GRAVE, CRAFTAX_BLOCK_GRAVE, CRAFTAX_BLOCK_WALL, CRAFTAX_BLOCK_WALL},
        {CRAFTAX_BLOCK_WALL_MOSS, CRAFTAX_BLOCK_GRAVE2, CRAFTAX_BLOCK_GRAVE3, CRAFTAX_BLOCK_SAPPHIRE, CRAFTAX_BLOCK_RUBY},
        {0.1f, 0.333f, 0.5f, 0.0f, 0.0f},
        CRAFTAX_BLOCK_PATH,
        CRAFTAX_BLOCK_GRAVE,
        CRAFTAX_BLOCK_WALL,
        CRAFTAX_BLOCK_NECROMANCER,
        CRAFTAX_BLOCK_PATH,
        false,
        false,
        5.0f,
        1.0f,
        10.0f,
        10.0f,
        0.0f,
        0.7f,
        0.6f,
        0.95f,
        -1.0f,
    },
};

static const CraftaxDungeonConfig CRAFTAX_DUNGEON_CONFIGS[3] = {
    {CRAFTAX_BLOCK_PATH, CRAFTAX_BLOCK_FOUNTAIN, CRAFTAX_BLOCK_PATH},
    {CRAFTAX_BLOCK_ENCHANTMENT_TABLE_ICE, CRAFTAX_BLOCK_WATER, CRAFTAX_BLOCK_WATER},
    {CRAFTAX_BLOCK_ENCHANTMENT_TABLE_FIRE, CRAFTAX_BLOCK_FOUNTAIN, CRAFTAX_BLOCK_PATH},
};

static const float CRAFTAX_ACHIEVEMENT_REWARD_MAP[CRAFTAX_NUM_ACHIEVEMENTS] = {
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 3.0f, 3.0f, 3.0f, 3.0f, 3.0f, 5.0f, 5.0f,
    5.0f, 8.0f, 8.0f, 8.0f, 3.0f, 3.0f, 3.0f, 3.0f,
    5.0f, 5.0f, 5.0f, 5.0f, 8.0f, 8.0f, 8.0f, 8.0f,
    8.0f, 8.0f, 3.0f, 3.0f, 3.0f, 3.0f, 3.0f, 5.0f,
    5.0f, 5.0f, 5.0f, 3.0f, 3.0f, 3.0f, 3.0f, 5.0f,
    5.0f, 5.0f, 5.0f,
};

static const float CRAFTAX_MAX_EPISODE_RETURN = 226.0f;
